/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BrowserData = IDL.Record({
  'source' : IDL.Text,
  'name' : IDL.Text,
  'version' : IDL.Text,
});
export const CombinedBrowserData = IDL.Record({
  'apkmirror' : IDL.Vec(BrowserData),
  'browserUpdate' : IDL.Vec(BrowserData),
  'statcounter' : IDL.Vec(BrowserData),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'fetchApkMirrorData' : IDL.Func([], [IDL.Text], []),
  'fetchBrowserUpdateData' : IDL.Func([], [IDL.Text], []),
  'fetchStatCounterData' : IDL.Func([], [IDL.Text], []),
  'getAllBrowserData' : IDL.Func([], [CombinedBrowserData], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BrowserData = IDL.Record({
    'source' : IDL.Text,
    'name' : IDL.Text,
    'version' : IDL.Text,
  });
  const CombinedBrowserData = IDL.Record({
    'apkmirror' : IDL.Vec(BrowserData),
    'browserUpdate' : IDL.Vec(BrowserData),
    'statcounter' : IDL.Vec(BrowserData),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'fetchApkMirrorData' : IDL.Func([], [IDL.Text], []),
    'fetchBrowserUpdateData' : IDL.Func([], [IDL.Text], []),
    'fetchStatCounterData' : IDL.Func([], [IDL.Text], []),
    'getAllBrowserData' : IDL.Func([], [CombinedBrowserData], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };